### ISSUE TITLE
Debs not created in jiohammer branch

### ISSUE THREAD

**Issue by bafna** [JioCloud/ceph#3]
While running make-debs.sh , the script stops with the error message : 

cp: cannot stat ‘/var/tmp/lxc/release/Ubuntu/WORKDIR/ceph-devel/debian/tmp/usr/bin/ceph_bench_log’: No such file or directory
dh_install: cp -a /var/tmp/lxc/release/Ubuntu/WORKDIR/ceph-devel/debian/tmp/usr/bin/ceph_bench_log debian/ceph-test//usr/bin/ returned exit code 1

This is the due to the fact that many binaries , the names can be found in src/debian/ceph-test.install are not created. Out of the 32 mentioned binaries, only the  first one gets created. 

This issue is not observed in the ceph upstream branch. The issue gets resolved when we comment out the binaries not getting created.

**Comment by rickysarraf** [comment]
Can you please provide the full log ?

**Comment by rickysarraf** [comment]
Here's what I'm looking for. Attached is my build log with all the details. Can you share the similar log from your setup ?

<script src="https://gist.github.com/rickysarraf/a9c61625658cc5401242.js"></script>

**Comment by bafna** [comment]
Please find the log at 
https://gist.github.com/bafna/f3e82bc7b6af9b367f92

**Comment by rickysarraf** [comment]
That log you've provided is against jiocloud/ceph master.
WHereas what I've built is against the jiohammer branch, based on our last conversation.

**Comment by bafna** [comment]
No Ritesh. It is jiohammer only as I can see from the following command

cp13@cp13:~/gaurav/jio/ceph$ git branch --list
* jiohammer
  master

**Comment by rickysarraf** [comment]
But your build log clearly says:
configure: RPM_RELEASE='5072.gda187c8'

Whereas the jiohammer branch was on: gbb51f92.

To correlate it to the repository, you can cut out the initial character <b><i>'g'</i></b> and use the remaining as a git commit id.

You should clean up your environment, re-clone,  `git checkout -b jiohammer origin/jiohammer`, and then do a build again.

**Comment by bafna** [comment]
Yes, I did that and was able to build with correct RPM_RELEASE.
