### ISSUE TITLE
Package Installation issue in JioHammer branch of ceph

### ISSUE THREAD

**Issue by bafna** [JioCloud/ceph#4]
Hi Ritesh,

On a clean machine , installing the ceph debs gives version errors and the installation stops.
Please find the complete log at 
https://gist.github.com/bafna/7bd775b34ddc3d2092a7

Also we get the same error with debs generated from ceph/hammer .

Interestingly, this error does not come while installing the manually downloaded debs from ceph.com . 
Can you please have a look into the issue?

**Comment by rickysarraf** [comment]
Are you sure that is a clean machine ? From the logs, it shows that it already had ceph installed.

Because the debs built by hand have a version lesser than what ceph.com provides.
So before you install your custom built debs, make sure there is no other ceph package installed.

The pkgs from ceph.com are: 9.0.0-943
vs
pkgs that you've built: 0.91-5072-gda187c8-1

**Comment by bafna** [comment]
Yes, it is a clean machine. I cleaned it manually though . 

Just to be sure, I created a new VM and did the same thing and I am still getting the same error .

" dpkg: dependency problems prevent configuration of ceph:
ceph depends on ceph-common (>= 9.0.0-943); however:
Package ceph-common is not installed. "

**Comment by rickysarraf** [comment]
Initially, you mentioned that ceph packages from ceph.com did not have any issues. But these packages in the last comment look to be from Ceph.

Anyways, irrespective of where you get the packages from, if the packages were built properly, they will install fine. In this case, I just tested the build deb packages on a local <b>clean</b> environment. By clean, I mean no previous trace of ceph pacakges.



ubuntu@bafna:/var/tmp/lxc/release/Ubuntu/WORKDIR$ sudo dpkg -i ceph_0.94.2-109-gbb51f92-1_amd64.deb ceph-common_0.94.2-109-gbb51f92-1_amd64.deb ceph-fs-common_0.94.2-109-gbb51f92-1_amd64.deb  ceph-fuse_0.94.2-109-gbb51f92-1_amd64.deb ceph-mds_0.94.2-109-gbb51f92-1_amd64.deb librados2_0.94.2-109-gbb51f92-1_amd64.deb librbd1_0.94.2-109-gbb51f92-1_amd64.deb python-rados_0.94.2-109-gbb51f92-1_amd64.deb python-cephfs_0.94.2-109-gbb51f92-1_amd64.deb python-rbd_0.94.2-109-gbb51f92-1_amd64.deb libcephfs1_0.94.2-109-gbb51f92-1_amd64.deb 

(Reading database ... 17318 files and directories currently installed.)
Preparing to unpack ceph_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking ceph (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack ceph-common_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking ceph-common (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack ceph-fs-common_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking ceph-fs-common (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack ceph-fuse_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking ceph-fuse (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack ceph-mds_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking ceph-mds (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack librados2_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking librados2 (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack librbd1_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking librbd1 (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack python-rados_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking python-rados (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack python-cephfs_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking python-cephfs (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Preparing to unpack python-rbd_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking python-rbd (0.94.2-109-gbb51f92-1) over (0.94.2-109-gbb51f92-1) ...
Selecting previously unselected package libcephfs1.
Preparing to unpack libcephfs1_0.94.2-109-gbb51f92-1_amd64.deb ...
Unpacking libcephfs1 (0.94.2-109-gbb51f92-1) ...
Setting up ceph-fs-common (0.94.2-109-gbb51f92-1) ...
Setting up ceph-fuse (0.94.2-109-gbb51f92-1) ...
Setting up librados2 (0.94.2-109-gbb51f92-1) ...
Setting up librbd1 (0.94.2-109-gbb51f92-1) ...
Setting up python-rados (0.94.2-109-gbb51f92-1) ...
Setting up python-rbd (0.94.2-109-gbb51f92-1) ...
Setting up libcephfs1 (0.94.2-109-gbb51f92-1) ...
Setting up python-cephfs (0.94.2-109-gbb51f92-1) ...
Setting up ceph-common (0.94.2-109-gbb51f92-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up ceph (0.94.2-109-gbb51f92-1) ...
ceph-all start/running
Processing triggers for ureadahead (0.100.0-16) ...
Setting up ceph-mds (0.94.2-109-gbb51f92-1) ...
ceph-mds-all start/running
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for ureadahead (0.100.0-16) ...

ubuntu@bafna:/var/tmp/lxc/release/Ubuntu/WORKDIR$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by bafna** [comment]
This issue was coming due to tags not pushed to the remote.  Thanks @rickysarraf for pushing the tags on the jiohammer branch. Now the packages can be installed successfully. Closing the issue.
